// <auto-generated />
using System;
using LojaShopping.OrderAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaShopping.OrderAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaShopping.OrderAPI.Model.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_produto");

                    b.Property<long>("OrderHeaderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("order_detail");
                });

            modelBuilder.Entity("LojaShopping.OrderAPI.Model.OrderHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CVV")
                        .HasColumnType("longtext")
                        .HasColumnName("CVV");

                    b.Property<int>("CarrTotalItens")
                        .HasColumnType("int")
                        .HasColumnName("carr_total_itens");

                    b.Property<string>("CouponCode")
                        .HasColumnType("longtext")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime>("DataOrdem")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_ordem");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_compra");

                    b.Property<decimal>("DescontoTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("desconto_total");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("MesAnoExpiracao")
                        .HasColumnType("longtext")
                        .HasColumnName("mes_ano_expiracao");

                    b.Property<string>("NumeroCartao")
                        .HasColumnType("longtext")
                        .HasColumnName("numero_cartao");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("longtext")
                        .HasColumnName("primeiro_nome");

                    b.Property<bool>("StatusPagamento")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status_pagamento");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.Property<string>("UltimoNome")
                        .HasColumnType("longtext")
                        .HasColumnName("ultimo_nome");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_final");

                    b.HasKey("Id");

                    b.ToTable("order_header");
                });

            modelBuilder.Entity("LojaShopping.OrderAPI.Model.OrderDetail", b =>
                {
                    b.HasOne("LojaShopping.OrderAPI.Model.OrderHeader", "OrderHeader")
                        .WithMany("CarrDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("LojaShopping.OrderAPI.Model.OrderHeader", b =>
                {
                    b.Navigation("CarrDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
