// <auto-generated />
using LojaShopping.CupomAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaShopping.CupomAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LojaShopping.CupomAPI.Model.Cupom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CodCupom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Cod_Cupom");

                    b.Property<decimal>("DescontoTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Desconto_Total");

                    b.HasKey("Id");

                    b.ToTable("cupom");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CodCupom = "ERUDIO_2022_10",
                            DescontoTotal = 10m
                        },
                        new
                        {
                            Id = 2L,
                            CodCupom = "ERUDIO_2022_15",
                            DescontoTotal = 15m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
